version: "2.2"

services:
  mysql:
    image: mysql:5.7
    hostname: mysql
    container_name: mysql
    mem_limit: 1g
    restart: on-failure
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: slurm_acct_db
      MYSQL_USER: slurm
      MYSQL_PASSWORD: password
    volumes:
      - var_lib_mysql:/var/lib/mysql

#  nfsserver:
#    image: itsthenetwork/nfs-server-alpine:12
#    container_name: nfsserver
#    hostname: nfsserver
#    restart: unless-stopped
#    privileged: true
#    environment:
#      - SHARED_DIRECTORY=/nfs
#    volumes:
#      - /Volumes/lfs1/docker-nfs/:/nfs
#    expose:
#      - 2049

  slurmdbd:
    image: slurm-docker-cluster:21.08.6
    build:
      context: .
      dockerfile: Dockerfile
    command: ["slurmdbd"]
    container_name: slurmdbd
    hostname: slurmdbd
    mem_limit: 1g
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - var_log_slurm:/var/log/slurm
      - nfs_data:/nfs
      - user_home:/home
    expose:
      - "6819"
    depends_on:
      - "mysql"

  slurmctld:
    image: slurm-docker-cluster:21.08.6
    command: ["slurmctld"]
    container_name: slurmctld
    hostname: slurmctld
    mem_limit: 1g
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - nfs_data:/nfs
      - user_home:/home
    ports:
      - "2222:22"
    depends_on:
      - "slurmdbd"

  c1:
    image: slurm-docker-cluster:21.08.6
    command: ["slurmd"]
    hostname: c1
    container_name: c1
    mem_limit: 2g
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - nfs_data:/nfs
      - user_home:/home
    expose:
      - "6818"
    depends_on:
      - "slurmctld"

  c2:
    image: slurm-docker-cluster:21.08.6
    command: ["slurmd"]
    hostname: c2
    container_name: c2
    mem_limit: 2g
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - nfs_data:/nfs
      - user_home:/home
    expose:
      - "6818"
    depends_on:
      - "slurmctld"

  c3:
    image: slurm-docker-cluster:21.08.6
    command: ["slurmd"]
    hostname: c3
    container_name: c3
    mem_limit: 2g
    volumes:
      - etc_munge:/etc/munge
      - etc_slurm:/etc/slurm
      - slurm_jobdir:/data
      - var_log_slurm:/var/log/slurm
      - nfs_data:/nfs
      - user_home:/home
    expose:
      - "6818"
    depends_on:
      - "slurmctld"

volumes:
  etc_munge:
  etc_slurm:
  slurm_jobdir:
  var_lib_mysql:
  var_log_slurm:
  user_home:
  nfs_data:
    driver: local
    driver_opts:
      type: nfs
      o: nfsvers=3,addr=mimir.isi.edu,rw
      device: ":/mnt/scitech/scratch2-90-days/slurm"
